import type { z } from "zod";
import type { musicSchema } from "$lib/content/schema";

export const musicEntries: (z.input<typeof musicSchema> & { slug: string })[] =
	[
		{
			slug: "absolution",
			link: "https://open.spotify.com/album/2Eq6RyxCm7qEAF2YLOxa4s?si=tDcJ6gAGSTW5QG05mimMMA",
			kind: "album",
			title: "absolution",
			artist: "muse",
			year: 2003,
			cover: "/music/absolution.jpg",
			color: "#c8caca",
		},
		{
			slug: "equus-asinus",
			link: "https://open.spotify.com/album/7dJPDPUi94jA91VxG4vZb3?si=XDryAS6PQNWxppLk1L9Aqw",
			kind: "album",
			title: "equus asinus",
			artist: "men i trust",
			year: 2025,
			cover: "/music/equus-asinus.jpg",
			color: "#797160",
		},
		{
			slug: "grief-chapter",
			link: "https://open.spotify.com/album/5sMSJ6uAozdrqFELMwl3NU?si=Vkapus-WR9CuMqrWViju3Q",
			kind: "album",
			title: "grief chapter",
			artist: "mother mother",
			year: 2024,
			cover: "/music/grief-chapter.jpg",
			video: "/music/grief-chapter.mp4",
			color: "#da1202",
		},
		{
			slug: "kin",
			link: "https://open.spotify.com/album/5yccZqBhhSqWndfKVjNZQY?si=NhI_r4mDSGKwxPrexGfnyw",
			kind: "album",
			title: "kin",
			artist: "electric guest",
			year: 2019,
			cover: "/music/kin.jpg",
			video: "/music/kin.mp4",
			color: "#ffffff",
		},
		{
			slug: "life-is-but-a-dream",
			link: "https://open.spotify.com/album/50YNY0xy9uJ0U9eFQBdLJa?si=X_CkAKxdR1uZVA7Kin-BUA",
			kind: "album",
			title: "life is but a dream",
			artist: "avenged sevenfold",
			year: 2023,
			cover: "/music/life-is-but-a-dream.jpg",
			video: "/music/life-is-but-a-dream.mp4",
			color: "#c8caca",
		},
		{
			slug: "melt",
			link: "https://open.spotify.com/album/4Arf0rqtYsnJ5hhscuqCLB?si=yGb97to6TYGlpGT2RI5Ohw",
			kind: "album",
			title: "melt",
			artist: "not for radio",
			year: 2025,
			cover: "/music/melt.jpg",
			color: "#080808",
		},
		{
			slug: "spirit-mission",
			link: "https://open.spotify.com/album/31t6VcIOZ3WqsSH2F9Zcy0?si=VwIzS0E1QyaVXgc2es2PUA",
			kind: "album",
			title: "spirit mission",
			artist: "sure sure",
			year: 2022,
			cover: "/music/spirit-mission.jpg",
			color: "#0e0e0f",
		},
		{
			slug: "submarine",
			link: "https://open.spotify.com/album/03guxdOi12XJbnvxvxbpwG?si=RbcC9pszSEuuIiEq3C_TFw",
			kind: "album",
			title: "submarine",
			artist: "the marías",
			year: 2024,
			cover: "/music/submarine.jpg",
			video: "/music/submarine.mp4",
			color: "#c8caca",
		},
		{
			slug: "the-wow!-signal",
			link: "https://open.spotify.com/album/6TObgE5QDLYzA3Exu5vGhS?si=7lqdFzNESSy7zsOIRNwtNQ",
			kind: "album",
			title: "the wow! signal",
			artist: "muse",
			year: 2026,
			cover: "/music/the-wow!-signal.jpg",
			video: "/music/the-wow!-signal.mp4",
			color: "#c8caca",
		},
		{
			slug: "yumeno-garden",
			link: "https://open.spotify.com/album/32S8pHV6mMJTg5lLZeb3sr?si=67NiH2pdThi57LUPdY8yeA",
			kind: "album",
			title: "yumeno garden",
			artist: "last dinosaurs",
			year: 2018,
			cover: "/music/yumeno-garden.jpg",
			color: "#fbab2b",
		},
	];
